<a href="https://colab.research.google.com/github/jaewon00o0/kbu-2.1/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%EA%B4%80%EB%A6%AC%EB%A1%A0%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EC%88%98%EC%B9%98%ED%99%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from IPython.display import display

In [2]:
url = 'https://raw.githubusercontent.com/ancestor9/data/main/customers.csv'
df = pd.read_csv(url)

In [4]:
print("[전처리 전] 원본 데이터 5줄 미리보기:")
display(df.head())

[전처리 전] 원본 데이터 5줄 미리보기:

,고객ID,성별,결제수단,거주지,회원등급,만족도,최근접속시간(시),선호제품군_적정온도,나이,구매수량,총결제금액
0,CUST_0001,남성,휴대폰결제,대구,Gold,2,1,27.0,34,7,760355
1,CUST_0002,여성,계좌이체,대구,Gold,5,15,24.6,20,42,727001
2,CUST_0003,여성,신용카드,광주,Gold,1,6,20.3,51,8,618787
3,CUST_0004,여성,계좌이체,서울,VVIP,5,20,16.8,19,29,434545
4,CUST_0005,여성,계좌이체,광주,Gold,3,6,23.5,53,45,604750

In [5]:
categorical_columns = df.select_dtypes(include=['object', 'category']).columns

In [6]:
df_processed = pd.get_dummies(df, columns=categorical_columns, drop_first=False, dtype=int)

In [10]:
print(" [전처리 후] 모든 데이터가 수치화된 데이터셋 5줄 미리보기:")
display(df_processed.head())

 [전처리 후] 모든 데이터가 수치화된 데이터셋 5줄 미리보기:

,만족도,최근접속시간(시),선호제품군_적정온도,나이,구매수량,총결제금액,고객ID_CUST_0001,고객ID_CUST_0002,고객ID_CUST_0003,고객ID_CUST_0004,...,거주지_경기,거주지_광주,거주지_대구,거주지_부산,거주지_서울,회원등급_Bronze,회원등급_Gold,회원등급_Silver,회원등급_VIP,회원등급_VVIP
0,2,1,27.0,34,7,760355,1,0,0,0,...,0,0,1,0,0,0,1,0,0,0
1,5,15,24.6,20,42,727001,0,1,0,0,...,0,0,1,0,0,0,1,0,0,0
2,1,6,20.3,51,8,618787,0,0,1,0,...,0,1,0,0,0,0,1,0,0,0
3,5,20,16.8,19,29,434545,0,0,0,1,...,0,0,0,0,1,0,0,0,0,1
4,3,6,23.5,53,45,604750,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0